secret:
  accessKey:
  secretKey:
certs:
  - domain: astat.cn
    tlsName: star-astat-cn
    tlsNamespace: default
  - domain: astatium.com
    tlsName: star-astatium-com
    tlsNamespace: default
common:
  baseURL: 'https://api.su.baidu.com/'
  signatureMethod: HMAC-SHA1
  removeExpiredCert: false
  checkInterval:  2h # two hours
  syncRetryTimes: 3
