---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yunjiasu-secret
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yunjiasu-secret
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yunjiasu-secret
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
