---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yunjiasu-secret
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yunjiasu-secret
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yunjiasu-secret
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: yunjiasu-chenyroger
  namespace: default
data:
  config.yaml: |-
    secret:
      accessKey:
      secretKey:
    certs:
      - domain: astat.cn
        tlsName: star-astat-cn # your k8s secret name
        tlsNamespace: default
    common:
      baseURL: 'https://api.su.baidu.com/'
      signatureMethod: HMAC-SHA1
      checkInterval:  2h # two hours
      syncRetryTimes: 3
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: yunjiasu-deploy
  namespace: default
spec:
  selector:
    matchLabels:
      app: yunjiasu-deploy
  template:
    metadata:
      labels:
        app: yunjiasu-deploy
    spec:
      volumes:
        - name: config
          configMap:
            name: yunjiasu-chenyroger
            defaultMode: 420
      containers:
        - name: yunjiasu
          image: 'ccr.ccs.tencentyun.com/astatium.com/yunjiasu'
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /mnt/config.yaml
              subPath: config.yaml
          terminationMessagePolicy: File
          imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: baidu-bj
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule